# Generated by Django 3.0a1 on 2019-10-21 21:40

import Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date_Formats',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Types', models.CharField(choices=[(Application.models.choice('dd:mm:yyyy'), 'dd:mm:yyyy'), (Application.models.choice('mm:dd:yyyy'), 'mm:dd:yyyy'), (Application.models.choice('yyyy:mm:dd'), 'yyyy:mm:dd')], max_length=10)),
            ],
        ),
    ]
