# Generated by Django 2.2.5 on 2019-10-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_account_client_client_account_transactions_vendor_vendor_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AFName', models.CharField(max_length=20)),
                ('ALName', models.CharField(max_length=20)),
                ('Quote', models.TextField()),
            ],
        ),
    ]
