# Generated by Django 2.2.5 on 2019-10-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Late_Fee_Rate',
            field=models.FloatField(default=0),
        ),
    ]
