# Generated by Django 2.2.5 on 2019-10-19 10:38

import Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_date_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_formats',
            name='Types',
            field=models.CharField(choices=[(Application.models.choice('dd:mm:yyyy'), 'dd:mm:yyyy'), (Application.models.choice('mm:dd:yyyy'), 'mm:dd:yyyy'), (Application.models.choice('yyyy:mm:dd'), 'yyyy:mm:dd')], max_length=10),
        ),
    ]
