# Generated by Django 3.0a1 on 2019-10-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_account_client_client_account_transactions_vendor_vendor_account'),
        ('Application', '0009_auto_20191017_1332'),
    ]

    operations = [
    ]
