# Generated by Django 3.0a1 on 2019-10-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_merge_20191018_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='Transaction_id',
            new_name='Transaction_Id',
        ),
        migrations.AddField(
            model_name='company',
            name='Base_Currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Application.Currency'),
        ),
        migrations.AlterField(
            model_name='client',
            name='Pin_Code',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='Pin_Code',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
